# Generated by Django 4.1.2 on 2022-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="회사명")),
                (
                    "nation",
                    models.CharField(
                        choices=[("korea", "한국"), ("japan", "일본"), ("china", "중국")],
                        max_length=28,
                        verbose_name="국가",
                    ),
                ),
                ("area", models.CharField(max_length=60, verbose_name="지역")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
