# Generated by Django 4.1.2 on 2022-10-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.CharField(max_length=40, verbose_name="채용포지션")),
                ("reward", models.PositiveIntegerField(verbose_name="채용보상금")),
                ("description", models.TextField(verbose_name="채용내용")),
                ("skill", models.CharField(max_length=40, verbose_name="사용기술")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruits",
                        to="companies.company",
                        verbose_name="채용회사",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
